name: Generate release-artifacts
on:
  release:
    types:
      - created
      - released
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: wangyoucao577/go-release-action@v1.36
        with:
          overwrite: TRUE
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19
          binary_name: schema2json
          project_path: ./cmd
